### ISSUE TITLE
RuntimeBinderException and cshtml reference issues

### ISSUE THREAD

**Issue by EdL** [DalSoft/DalSoft.WebApi.HelpPage#3]
Hi, thanks for creating this package - it will be really useful.

I've installed it and it is working. I don't get any compile-time errors but I get several exceptions thrown in the VS output log whilst running:
`Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll`

Also, in all the cshtml views, none of the 'using' references are recognised and neither are Model, ViewBag or any of the code. I get `The name ViewBag does not exist in the current context`or `The type or namesapce ILookup<string, ApiDescription> could not be found (are you missing...)`.

Just wondering if anyone else is experienceing this or if any ideas on resolving?

Many thanks

**Comment by DalSoft** [comment]
Not seen any issues like that. But if you could give me access to code (github or zip) where this is happening and I'll take a look.

**Comment by EdL** [comment]
Thanks for the swift response. Unfortunately it's on private repo for work so can't share. I'll try using your package on a basic VS web.api template first and see if I experience similar issues.
Thanks

**Comment by DalSoft** [comment]
Sure if you can repoduce without any sensitive code let me know and I'll take a look.

**Comment by EdL** [comment]
[Test.zip](https://github.com/DalSoft/DalSoft.WebApi.HelpPage/files/274467/Test.zip)

Hi, I've created a test project (VS2015) which demonstrates the exception. It's just a self hosted web.api controller with your package added. If you run in debug and visit the help page you should  see the exception in the VS output log: 
`Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll`

Thanks

**Comment by DalSoft** [comment]
Just tried it and it worked for me. One thing it could be for some reason the xml for the documentation is not created. Try adding  `/// <summary>Hello</summary>`to one of the API methods to force the xml doc to be generated. Also can you verify that Test.XML is created in the bin folder.

Also try clean solution, then rebuild solution.

**Comment by EdL** [comment]
Hmmm. It does work for me, as in it generates the help page, just I get these exceptions thrown in the output log. The XML file is being generated. I have attached a screenshot showing the error highlighting in the template and exceptions on the output log.

So no exceptions in your log and no syntax errors on your .cshtml files? 

![image](https://cloud.githubusercontent.com/assets/4727866/15431279/04a6cc7c-1ea1-11e6-9770-6a7c76a5816e.png)

**Comment by DalSoft** [comment]
Right sorry I'm on the same page as you now, yes I do see the same error messages. This ins't anything to worry about the Visual Studio editor is trying to validate the Razor syntax ahead at time, because I'm using RazorEngine with some extensions I've written VS thinks there is a syntax error when is isn't. If you close all the .cshtml files and build you will see 0 errors. 

Hope that makes sense,

D

**Comment by EdL** [comment]
Ok, good to hear it's nothing to worry about.
Thanks for looking into it.
