### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by ryandanthony** [DalSoft/DalSoft.WebApi.HelpPage#4]
If you have a model that contains two types of the same name, but diff namespaces, it throws an InvalidOperationException:

"A model description could not be created. Duplicate model name 'XXX' was found for types 'Namespace1.XXX' and 'Namespace2.XXX'

Add a parameter for useFullTypeNameInModel  = false.

**Comment by DalSoft** [comment]
Try using the ModelName attribute:

``` cs
[ModelName("NameYouWouldLikeToDisplay")]
public class HasSameNameButDifferentNamespace 
{
}
```

I'll add this to the documentation when I get a chance.
