### ISSUE TITLE
On OWIN self-hosted applications, using attribute routing breaks the documentation page

### ISSUE THREAD

**Issue by gdyrrahitis** [DalSoft/DalSoft.WebApi.HelpPage#6]
I am self-hosting an ASP.NET Web API application with OWIN.
The `/help` route breaks when attribute routing is set in application.

**Comment by DalSoft** [comment]
I use it with attribute routing and it works fine, could be something specific. Would you mind posting the code that is breaking and I'll take a look at it for you.

**Comment by gdyrrahitis** [comment]
I am just creating a minimal self-hosted Web API application. When turning on attribute routing the `/help` page does not work.

Program.cs

```
using System;
using Microsoft.Owin.Hosting;

class Program
{
    static void Main(string[] args)
    {
        using (WebApp.Start<Startup>("http://localhost:12345"))
        {
            Console.WriteLine("Listening to port 12345");
            Console.WriteLine("Press enter to end..");
            Console.ReadLine();
        }
    }
}
```

Startup.cs

```
using System.Web.Http;
using DalSoft.WebApi.HelpPage;
using Owin;

public class Startup
{
    public static void Configuration(IAppBuilder app)
    {
        var configuration = new HttpConfiguration();

        configuration.MapHttpAttributeRoutes();
        configuration.Routes.MapHttpRoute("DefaultApi", "api/{controller}/{id}", defaults: new { controller = "values", id = RouteParameter.Optional });

        app.UseWebApiHelpPage(configuration);
        app.UseWebApi(configuration);
    }
}
```

On Visual Studio 2015, Output window, I get the following message when I navigate to `/help`:
`Exception thrown: 'System.InvalidOperationException' in mscorlib.dll`

After enabling the Common Language Runtime Exceptions, the exception show is:

```
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll

Additional information: The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.
```

Installed:
- DalSoft.WebApi.HelpPage@0.0.7
- Microsoft.Owin@3.0.1
- Microsoft.Owin.SelfHost@3.0.1
- Microsoft.AspNet.WebApi.Owin@5.2.3

And their additional dependencies.

**Comment by DalSoft** [comment]
Hi,

Change your startup.cs to:

``` c#
app.UseWebApi(configuration);
app.UseWebApiHelpPage(configuration);
```

The way the WebApi middleware works means app.UseWebApiHelpPage needs to be called after app.UseWebApi. For more information why you have to do this with WebApi see my SO answer http://stackoverflow.com/questions/18921215/cant-get-asp-net-web-api-2-help-pages-working-when-using-owin

**Comment by gdyrrahitis** [comment]
Thanks, now it is working. Closing issue.
